version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  producer:
    build:
      context: .
      dockerfile: Dockerfile.Producer
    environment:
      AMQP_URI: amqp://guest:guest@rabbitmq:5672/
      PREFETCH_COUNT: 2
      REDIS_URI: redis:6379
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  errorworker1:
    build:
      context: .
      dockerfile: Dockerfile.ErrorWorker
    environment:
      AMQP_URI: amqp://guest:guest@rabbitmq:5672/
      PREFETCH_COUNT: 1
      REDIS_URI: redis:6379
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  errorworker2:
    build:
      context: .
      dockerfile: Dockerfile.ErrorWorker
    environment:
      AMQP_URI: amqp://guest:guest@rabbitmq:5672/
      PREFETCH_COUNT: 1
      REDIS_URI: redis:6379
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  infosubscriber-grafana:
    build:
      context: .
      dockerfile: Dockerfile.InfoSubscriber
    environment:
      AMQP_URI: amqp://guest:guest@rabbitmq:5672/
      PREFETCH_COUNT: 10
    command: grafana
    depends_on:
      rabbitmq:
        condition: service_healthy

  infosubscriber-elk:
    build:
      context: .
      dockerfile: Dockerfile.InfoSubscriber
    environment:
      AMQP_URI: amqp://guest:guest@rabbitmq:5672/
      PREFETCH_COUNT: 10
    command: elk
    depends_on:
      rabbitmq:
        condition: service_healthy
